//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webAPIFA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionEntry
    {
        public int TransactionID { get; set; }
        public int JournalDebit { get; set; }
        public int JournalCredit { get; set; }
        public int JournalId { get; set; }
    }
}
